### ISSUE TITLE
python 3 update is required

### ISSUE THREAD

**Issue by decarlof** [alexrudy/sphinx-idl#1]
the [current version](https://github.com/alexrudy/sphinx-idl/tree/978122d10a01caa1a834bcb5ac5c789f4dc83cc5) of sphinx-idl does not run under Python 3

**Comment by alexrudy** [comment]
closed by #2

**Comment by decarlof** [comment]
thanks a lot @alexrudy. All works as expected now when I build locally but I am not able to build on readthedocs, I will describe in more details in a new ticket.
